name: Delete old workflow runs
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: Elite-Redux/eliteredux
          retain_days: 1
          keep_minimum_runs: 20000
